from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

class DocumentInput(BaseModel):
    content: str = Field(..., description="The main text content of the document.")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Optional metadata for the document, e.g., {'source': 'filename.pdf'}")

class DocumentOutput(BaseModel):
    doc_id: str = Field(..., description="The unique identifier for the document.")
    content: str = Field(..., description="The main text content of the document.")
    metadata: Dict[str, Any] = Field(..., description="Metadata associated with the document.")

class DocumentMinimalOutput(BaseModel):
    doc_id: str = Field(..., description="The unique identifier for the document.")
    message: str = Field(default="Document processed successfully.")

class ChatMessageInput(BaseModel):
    session_id: str = Field(..., description="Unique identifier for the conversation session.")
    user_message: str = Field(..., description="The message sent by the user.")

class RetrievedDocInfo(BaseModel):
    doc_id: Optional[str] = Field(None, description="ID of the retrieved document (if available in metadata).")
    score: Optional[float] = Field(None, description="Similarity score of the retrieved document (if available).")
    content: Optional[str] = Field(None, description="The text content of the retrieved document chunk.")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Metadata of the retrieved document.")


class ChatMessageOutput(BaseModel):
    session_id: str = Field(..., description="Unique identifier for the conversation session.")
    user_message: str = Field(..., description="The message sent by the user.")
    ai_response: str = Field(..., description="The response generated by the AI.")
    retrieved_docs: Optional[List[RetrievedDocInfo]] = Field(None, description="List of relevant documents retrieved from the vector store.")

# For health check
class HealthStatus(BaseModel):
    status: str = Field(default="ok")
    mongo_status: str = Field(default="pending")
    redis_status: str = Field(default="pending")
    openai_status: str = Field(default="pending")
    pinecone_status: str = Field(default="pending")
    pinecone_index_status: str = Field(default="pending")
